version: "3.8"

services:
    web:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./project:/project
        ports:
            - "8000:8000"
        depends_on:
            - db
            - cache
    db:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=tasks_db
            - POSTGRES_USER=postgres 
            - POSTGRES_PASSWORD=1234
    cache:
        image: redis
        container_name: redis 
